= Chamber Choir at Georgia Tech: Bylaws
:revdate: Revised April 24, 2023
:version-label!:

== Article I: Other Officers
=== Section 1: Section Leaders

The Section Leaders shall be appointed by the ensemble Director in collaboration with the officer team.
New Section Leaders, of which there shall be at least one (1) but no more than two (2) per section, shall be appointed each semester.
Section Leaders shall be appointed during the first four (4) weeks of the semester.
Chamber members shall be solicited for suggestions on the appointment process at least three (3) weeks prior to appointments.
The ensemble Director, in collaboration with the officer team, shall agree upon the appointment process and announce its details to the choir in writing at least one (1) week prior to appointments.
Section Leaders must be a member of the section to which they are being appointed and must have been a member of the Georgia Tech Chamber Choir for at least one semester prior to their term as Section Leader.
The _President_ and _Vice President of Internal Affairs_ are ineligible to be appointed section leader.

Section Leaders shall have the following responsibilities:

* Exhibiting musical leadership, identification of problems, and rehearsal discipline;
* Planning and running sectional rehearsals;
* Recording attendance during sectional rehearsals;
* Reporting attendance of sectional rehearsals to the VP of Internal Affairs; and, 
* Coordinating and executing sectional social activities.

== Article II: Other Rehearsals
=== Section 1: Sectional Rehearsals

Chamber members will be required to attend two, 1-hour rehearsals each month outside of the regular rehearsal time.
The meeting time will be determined by the section leader at the beginning of the semester. 
